### ISSUE TITLE
Crashes on certain words

### ISSUE THREAD

**Issue by VIEWVIEWVIEW** [radomirbosak/duden#146]
Example export:
```
$ python run_duden.py --export Meme > tests/test_data/Meme.yaml
```

Results in the following crash:
```
~/duden$ python run_duden.py --export Meme > tests/test_data/Meme.yaml
Traceback (most recent call last):
  File "run_duden.py", line 4, in <module>
    main()
  File "/home/w/duden/duden/cli.py", line 173, in main
    display_word(word, args)
  File "/home/w/duden/duden/cli.py", line 61, in display_word
    yaml_string = yaml.dump(word.export(),
  File "/home/w/duden/duden/word.py", line 298, in export
    worddict[attribute] = getattr(self, attribute, None)
  File "/home/w/duden/duden/word.py", line 61, in name
    name, _ = self.title.split(', ')
ValueError: too many values to unpack (expected 2)
```

Apparently there is a crash on the word "Meme" due to too many splits of the `word.name` and `word.article` propety. This can be fixed by setting the `maxsplit` in the split call:
```
name, _ = self.title.split(', ', 1)
```
https://docs.python.org/3/library/stdtypes.html#str.split

**Comment by radomirbosak** [comment]
Maybe a more robust way to get the name and article would be to locate the `lemma__*` spans.
![image](https://user-images.githubusercontent.com/4988740/136238823-2e426bf6-de57-46c4-aa20-81a6e18d1d0b.png)
