### ISSUE TITLE
Word "Qat" crashes the program

### ISSUE THREAD

**Issue by radomirbosak** [radomirbosak/duden#51]
```console
$ duden Qat
Qat, das
========
Traceback (most recent call last):
  File "/home/user/.local/bin/duden", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/duden/main.py", line 610, in main
    display_word(word, args)
  File "/home/user/.local/lib/python3.6/site-packages/duden/main.py", line 554, in display_word
    word.describe()
  File "/home/user/.local/lib/python3.6/site-packages/duden/main.py", line 79, in describe
    print(_('Word type: ') + self.part_of_speech)
TypeError: must be str, not NoneType
```

**Comment by jorgesumle** [comment]
When fixed with pull request #52 the program doesn't fail, but it doesn't display the useful *Verweis*. If it's trivial to implement and there are other pages with *Verweise*, the program should display this information.
